-- Users Table
CREATE TABLE IF NOT EXISTS public.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    hashed_password TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Folders Table
CREATE TABLE IF NOT EXISTS public.folders (
    folder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(user_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by BIGINT,
    updated_by BIGINT
);

-- Curriculums Table
CREATE TABLE IF NOT EXISTS public.curriculums (
    curriculum_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id BIGINT REFERENCES public.curriculums(curriculum_id),
    level INTEGER DEFAULT 1,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by BIGINT,
    updated_by BIGINT
);

-- Problems Table
CREATE TABLE IF NOT EXISTS public.problems (
    problem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(user_id) ON DELETE CASCADE,
    folder_id BIGINT REFERENCES public.folders(folder_id) ON DELETE SET NULL,
    curriculum_id BIGINT REFERENCES public.curriculums(curriculum_id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    problem_image_url TEXT,
    answer_image_url TEXT,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by BIGINT,
    updated_by BIGINT
);

-- Hints Table
CREATE TABLE IF NOT EXISTS public.hints (
    hint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT REFERENCES public.problems(problem_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    step_number INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by BIGINT,
    updated_by BIGINT
);

-- Study Sessions Table
CREATE TABLE IF NOT EXISTS public.study_sessions (
    study_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(user_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    mode TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by BIGINT,
    updated_by BIGINT
);

-- Study Session Curriculums (N:M)
CREATE TABLE IF NOT EXISTS public.study_session_curriculums (
    study_session_id BIGINT REFERENCES public.study_sessions(study_session_id) ON DELETE CASCADE,
    curriculum_id BIGINT REFERENCES public.curriculums(curriculum_id) ON DELETE CASCADE,
    PRIMARY KEY (study_session_id, curriculum_id)
);

-- Study Session Folders (N:M)
CREATE TABLE IF NOT EXISTS public.study_session_folders (
    study_session_id BIGINT REFERENCES public.study_sessions(study_session_id) ON DELETE CASCADE,
    folder_id BIGINT REFERENCES public.folders(folder_id) ON DELETE CASCADE,
    PRIMARY KEY (study_session_id, folder_id)
);

-- Solve Logs Table
CREATE TABLE IF NOT EXISTS public.solve_logs (
    solve_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(user_id) ON DELETE CASCADE,
    problem_id BIGINT REFERENCES public.problems(problem_id) ON DELETE CASCADE,
    study_session_id BIGINT REFERENCES public.study_sessions(study_session_id) ON DELETE SET NULL,
    solution TEXT,
    is_correct BOOLEAN DEFAULT FALSE,
    time_spent INTEGER DEFAULT 0,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
