-- Create Curriculums table
CREATE TABLE IF NOT EXISTS curriculums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id BIGINT REFERENCES curriculums(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add curriculum_id to problems table
ALTER TABLE problems 
ADD COLUMN IF NOT EXISTS curriculum_id BIGINT REFERENCES curriculums(id);

-- Ensure answer_image_url exists
ALTER TABLE problems 
ADD COLUMN IF NOT EXISTS answer_image_url TEXT;
