-- 1. Users (Simple placeholder)
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT,
    hashed_password TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Folders (Problem Books)
CREATE TABLE IF NOT EXISTS folders (
    folder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_by BIGINT REFERENCES users(user_id),
    updated_by BIGINT REFERENCES users(user_id)
);

-- 3. Curriculums (Math Hierarchy)
CREATE TABLE IF NOT EXISTS curriculums (
    curriculum_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id BIGINT REFERENCES curriculums(curriculum_id),
    level INTEGER DEFAULT 0,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_by BIGINT REFERENCES users(user_id),
    updated_by BIGINT REFERENCES users(user_id)
);

-- 4. Problems
CREATE TABLE IF NOT EXISTS problems (
    problem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    folder_id BIGINT REFERENCES folders(folder_id) ON DELETE SET NULL,
    curriculum_id BIGINT REFERENCES curriculums(curriculum_id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    problem_image_url TEXT,
    answer_image_url TEXT,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_by BIGINT REFERENCES users(user_id),
    updated_by BIGINT REFERENCES users(user_id)
);

-- 5. Hints
CREATE TABLE IF NOT EXISTS hints (
    hint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT REFERENCES problems(problem_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    step_number INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. SolveLogs
CREATE TABLE IF NOT EXISTS solve_logs (
    solve_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    problem_id BIGINT REFERENCES problems(problem_id) ON DELETE CASCADE,
    solution TEXT,
    is_correct BOOLEAN DEFAULT FALSE,
    time_spent INTEGER, -- in seconds
    image_url TEXT, -- solution image
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Study Sessions
CREATE TABLE IF NOT EXISTS study_sessions (
    study_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    mode TEXT DEFAULT 'all', -- 'all', 'wrong', 'not_attempted'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Study Session Targets (Curriculums)
CREATE TABLE IF NOT EXISTS study_session_curriculums (
    study_session_id BIGINT REFERENCES study_sessions(study_session_id) ON DELETE CASCADE,
    curriculum_id BIGINT REFERENCES curriculums(curriculum_id) ON DELETE CASCADE,
    PRIMARY KEY (study_session_id, curriculum_id)
);

-- 9. Study Session Targets (Folders)
CREATE TABLE IF NOT EXISTS study_session_folders (
    study_session_id BIGINT REFERENCES study_sessions(study_session_id) ON DELETE CASCADE,
    folder_id BIGINT REFERENCES folders(folder_id) ON DELETE CASCADE,
    PRIMARY KEY (study_session_id, folder_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_problems_folder ON problems(folder_id);
CREATE INDEX IF NOT EXISTS idx_problems_curriculum ON problems(curriculum_id);
CREATE INDEX IF NOT EXISTS idx_solve_logs_user_problem ON solve_logs(user_id, problem_id);

-- Initial Seed Data
-- INSERT INTO users (username, email) VALUES ('student1', 'student1@example.com');
